substitutions:
  _DEXCOM_PROJECT_ID: spring-ajar
  _DEXCOM_NAMESPACE: germany
images:
  - "gcr.io/$PROJECT_ID/${_DEXCOM_PROJECT_ID}:$REVISION_ID"
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/${_DEXCOM_PROJECT_ID}:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/${_DEXCOM_PROJECT_ID}:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'rs/${_DEXCOM_PROJECT_ID}-rs'
      - 'spring-boot-container=gcr.io/$PROJECT_ID/${_DEXCOM_PROJECT_ID}:$REVISION_ID'
      - '--namespace=${_DEXCOM_NAMESPACE}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetes-p8-integrations-eu-dev-2'
