substitutions:
  DEXCOM_MICRO_SVC_PROJECT_NAME: _spring_board_ajar # default value
images:
  - "gcr.io/$PROJECT_ID/${DEXCOM_MICRO_SVC_PROJECT_NAME}:$REVISION_ID"
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/${DEXCOM_MICRO_SVC_PROJECT_NAME}:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/${DEXCOM_MICRO_SVC_PROJECT_NAME}:$REVISION_ID"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/${DEXCOM_MICRO_SVC_PROJECT_NAME}-dep'
      - 'gcr.io/$PROJECT_ID/${DEXCOM_MICRO_SVC_PROJECT_NAME}:$REVISION_ID'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=p8-integrations-eu-dev-2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetes-p8-integrations-eu-dev-2'