steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-board-ajar', '.']
images: ['gcr.io/$PROJECT_ID/spring-board-ajar']