#Info endpoints
info:
  company: Dexcom
  project: integrations

# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true
  info:
    git:
      mode: full

spring:
  application:
    name: spring-ajar
  cloud:
    kubernetes:
      config:
        name: spring-ajar
        namespace: germany
        sources:
          - name: spring-ajar
      reload:
        enabled: true
        mode: polling
        period: 2000
# Actuator endpoints
endpoints:
  cors:
    allowed-origins: "*"
  metrics:
    enabled: true
  configprops:
    enabled: true
  env:
    enabled: true
  beans:
    enabled: true

