#Info endpoints
info:
  company: Dexcom
  project: integrations

# Management endpoints
management:
  endpoint:
    restart:
      enabled:  true

spring:
  application:
    name: spring-ajar
  cloud:
    kubernetes:
      config:
        name: spring-ajar
        namespace: germany
        sources:
          - name: spring-ajar
      reload:
        enabled: true
        mode: polling
        period: 2000

