apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: ajar-spring-board-dep
  name: ajar-spring-board-dep
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ajar-spring-board-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ajar-spring-board-dep
    spec:
      containers:
      - image: gcr.io/p8-integrations-eu-dev-2/ajar-spring-board:9753e5c0656cc176b0afdf502421937cebf783d0
        imagePullPolicy: IfNotPresent
        name: ajar-spring-board
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
