apiVersion: v1
kind: Service
metadata:
  labels:
    app: ajar-spring-board-dep
  name: ajar-spring-board-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ajar-spring-board-dep
  sessionAffinity: None
  type: NodePort
