apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-ajar-dep
  name: spring-ajar-svc
  namespace: germany
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-ajar-dep
  sessionAffinity: None
  type: NodePort
